const tablaNombres = [
  "Drelil", 
  "Lirann", 
  "Sybil", 
  "Beatriz", 
  "Elgile", 
  "Lirathil", 
  "Theune", 
  "Breagan", 
  "Esme", 
  "Lisabeth", 
  "Wenain", 
  "Bronwyn", 
  "Griya", 
  "Moralil", 
  "Ygwal", 
  "Cannora", 
  "Henaine", 
  "Morgwen", 
  "Yslen", 
  "Arwel", 
  "Breglor", 
  "Grinwit", 
  "Melnax", 
  "Bevan", 
  "Canhoreal", 
  "Gruwid", 
  "Orthax", 
  "Boroth", 
  "Emrys", 
  "Gruwth", 
  "Triunein", 
  "Borrid", 
  "Ethex", 
  "Gwestin", 
  "Wenlan", 
  "Breagle", 
  "Gringle", 
  "Mannog", 
  "Yirmeor"
];

const tablaApellidos = [
  "Abernathy", 
  "Crumwaller", 
  "Harper", 
  "Swinney", 
  "Addercap", 
  "Dunswallow", 
  "Loomer", 
  "Thatcher", 
  "Burl", 
  "Getri", 
  "Malksmilk", 
  "Tolmen", 
  "Candlewick", 
  "Glass", 
  "Smythe", 
  "Weaver", 
  "Cormick", 
  "Harkness", 
  "Sunderman", 
  "Wolder"
];

const tablaTrasfondos = [
	"Alquimista", 
	"Carterista", 
	"Enterrador", 
	"Mago", 
	"Jugador", 
	"Cazador", 
	"Explorador", 
	"Mercader", 
	"Artista", 
	"Clérigo", 
	"Herbolario", 
	"Mercenario", 
	"Carnicero", 
	"Criado", 
	"Herrero", 
	"Minero", 
	"Carpintero", 
	"Criminal", 
	"Ladrón", 
	"Contrabandista"
];

const tablaFisicos = [
  "Atlético", 
	"Flácido", 
	"Bajo", 
	"Gordo", 
	"Enorme", 
	"Larguirucho", 
	"Escuálido", 
	"Musculoso", 
	"Escultural", 
	"Robusto" 
];

const tablaPieles = [
	"Bronceada", 
	"Pigmentada", 
	"Fofa", 
	"Ronchas", 
	"Marcadenacimiento", 
	"Rosácea", 
	"Marcas de viruela", 
	"Tatuada", 
	"Oscura", 
	"Tirante"
];

const tablaCabellos = [
  "Abundante", 
	"Largo", 
	"Calvo", 
	"Ondulado", 
	"Encrespado", 
	"Rizado", 
	"Escaso", 
	"Sucio", 
	"Grasiento", 
	"Trenzado"
];

const tablaRostros = [
  "Afilado", 
	"Desfigurado", 
	"Alargado", 
	"Huesudo", 
	"Cincelado", 
	"Pálido", 
	"Cuadrado", 
	"Perfecto", 
	"De mejillas hundidas", 
	"Ratonil" 
];

const tablaVoces = [
  "Cavernosa", 
	"Formal", 
	"Clara", 
	"Monótona", 
	"Directa", 
	"Resonante", 
	"Enigmática", 
	"Susurrante", 
	"Estridente", 
	"Tartamuda" 
];

const tablaVestimentas = [
"Antigua", 
"Ensangrentada", 
"Con barro", 
"Elegante", 
"De otro lugar", 
"Maloliente", 
"Desaliñada", 
"Sucia", 
"Deshilachada", 
"Uniforme"
];

const tablaVirtudes = [
  "Ambicioso", 
	"Precavido", 
	"Disciplinado", 
	"Sereno", 
	"Honorable", 
	"Sociable", 
	"Humilde", 
	"Tolerante", 
	"Misericordioso", 
	"Valiente" 
];

const tablaDefectos = [
  "Agresivo", 
	"Mentiroso", 
	"Amargado", 
	"Nervioso", 
	"Avaricioso", 
	"Perezoso", 
	"Codicioso", 
	"Rudo", 
	"Engreído", 
	"Vengativo" 
];

const tablaReputaciones = [
	"Ambicioso", 
	"Honrado", 
	"Bicho", 
	"raro", 
	"Patán", 
	"Desagradable", 
	"Peligroso", 
	"Divertido", 
	"Respetado", 
	"Holgazán", 
	"Sabio" 
];

const tablaDesgracias = [
  "Abandonado", 
	"Degradado", 
	"Adicto", 
	"Desheredado", 
	"Chantajeado", 
	"Desacreditado", 
	"Condenado", 
	"Exiliado", 
	"Defraudado", 
	"Maldito" 
];

const tablaEquipoParaExpediciones = [
	"Aceite combustible", 
	"Catalejo", 
	"Pico", 
	"Soga (8 m)", 
	"Amuleto contra espíritus", 
	"Gancho de agarre", 
	"Planta de acónito", 
	"Trampa grande", 
	"Antitoxina", 
	"Ganzúas", 
	"Polea", 
	"Vara (3 m)", 
	"Cadena (3 m)", 
	"Grilletes", 
	"Repelente", 
	"Varita de zahorí", 
	"Carreta (+4 espacio, voluminosa)", 
	"Odre para bucear", 
	"Saco grande", 
	"Yesquero"
];

const tablaHerramientas = [
  "Abrojos", 
	"Fuelle", 
	"Pala", 
	"Reloj de arena", 
	"Caña de pescar", 
	"Grasa", 
	"Palanca", 
	"Sellador", 
	"Cincel", 
	"Lima de metal", 
	"Pegamento", 
	"Serrucho", 
	"Clavos", 
	"Martillo", 
	"Pinzas de metal", 
	"Taladro manual", 
	"Cubo", 
	"Olla para cocinar", 
	"Red", 
	"Tiza"
];

const tablaBaratijas = [
  "Botella", 
	"Cuerno", 
	"Instrumento musical", 
	"Paquete de sal", 
	"Bote de alquitrán", 
	"Dados", 
	"Jabón", 
	"Perfume", 
	"Campanilla", 
	"Espejo", 
	"Joyas falsas", 
	"Pintura facial", 
	"Canicas", 
	"Esponja", 
	"Lupa", 
	"Pluma y tinta", 
	"Cordel", 
	"Incienso", 
	"Mazo de cartas", 
	"Silbato" 
];

const tablaHechizos = [
  "Acelerar", 
	"Cosificar", 
	"Hipnotizar", 
	"Oler", 
	"Acelerón primordial", 
	"Curar heridas", 
	"Hogar", 
	"Ordenar", 
	"Adherir", 
	"Desmontar", 
	"Identificar dueño", 
	"Pacificar", 
	"Aire líquido", 
	"Sustituir", 
	"Iluminar", 
	"Portal", 
	"Alterar gravedad", 
	"Detectar magia", 
	"Ilusión auditiva", 
	"Prisión astral", 
	"Amortiguador mágico", 
	"Disfraz", 
	"Ilusión visual", 
	"Proteger", 
	"Ancla", 
	"Dormir", 
	"Imagen especular", 
	"Puerta espejo", 
	"Antropomorfizar", 
	"Elasticidad", 
	"Intercambiar", 
	"Red", 
	"Apagar", 
	"Empujar"/"tirar", 
	"Intercambiar cuerpo", 
	"Repeler", 
	"Arrebatar", 
	"Encantar", 
	"Invocar cubo", 
	"Resbalar", 
	"Artilugio", 
	"Ensordecer", 
	"Invocar espíritu", 
	"Salto", 
	"Atadura invisible", 
	"Escudo", 
	"Invocar ídolo", 
	"Sentir", 
	"Atraer", 
	"Esculpir materia", 
	"Leer mentes", 
	"Señalar objetivo", 
	"Balbucear", 
	"Esfera nocturna", 
	"Levantar osamenta", 
	"Surgencia", 
	"Bengala", 
	"Espectáculo", 
	"Levitar", 
	"Telepatía", 
	"Brazo múltiple", 
	"Espesura", 
	"Machete", 
	"Telequinesis", 
	"Canicas", 
	"Espiar", 
	"Marca de mago", 
	"Teletransportar", 
	"Clasificar", 
	"Flor carnada", 
	"Mascarada", 
	"Terremoto", 
	"Codicia", 
	"Fobia", 
	"Miniaturizar", 
	"Toc-toc", 
	"Comprender", 
	"Forma bestial", 
	"Muro elemental", 
	"Toque helado", 
	"Confundir", 
	"Forma de humo", 
	"Nube de niebla", 
	"Trepar como araña", 
	"Cono de espuma", 
	"Forma de limo", 
	"Objeto animado", 
	"Velo", 
	"Controlar el clima", 
	"Foso", 
	"Odio", 
	"Visión", 
	"Controlar el tiempo", 
	"Frenesí", 
	"Oír susurros", 
	"Visión de rayos X", 
	"Controlar plantas", 
	"Grupo de animales", 
	"Ojo arcano", 
	"Visión verdadera" 
];
