const tablaNombres = [
  "Alaric",
  "Aldous",
  "Alton",
  "Archibald",
  "Arne",
  "Arthur",
  "Balthazar",
  "Bard",
  "Bartholomew",
  "Bartlett",
  "Basil",
  "Baxton",
  "Benedict",
  "Bennett",
  "Beorn",
  "Bertram",
  "Burchard",
  "Cadman",
  "Caspian",
  "Chadwick",
  "Clovis",
  "Conrad",
  "Corbett",
  "Crispin",
  "Cyprian",
  "Cyrus",
  "Daegal",
  "Denis",
  "Destrian",
  "Drogo",
  "Eldon",
  "Ellis",
  "Elric",
  "Emil",
  "Erasmus",
  "Faustus",
  "Felix",
  "Finn",
  "Finnian",
  "Fitzhugh",
  "Florian",
  "Fox",
  "Galileo",
  "Giles",
  "Godfrey",
  "Godwin",
  "Grimwald",
  "Hamlin",
  "Hannibal",
  "Hildebrand",
  "Jasper",
  "Jeremiah",
  "Johan",
  "Jules",
  "Kenric",
  "Leif",
  "Leopold",
  "Leoric",
  "Lothar",
  "Lucian",
  "Merrick",
  "Milo",
  "Mordred",
  "Mortimer",
  "Neville",
  "Odel",
  "Ogden",
  "Orion",
  "Orvyn",
  "Osric",
  "Oswald",
  "Paschal",
  "Percival",
  "Peregrine",
  "Piers",
  "Quentin",
  "Randolf",
  "Redmaine",
  "Reinhold",
  "Rex",
  "Ricard",
  "Roland",
  "Rufus",
  "Silas",
  "Stilton",
  "Stratford",
  "Sylvio",
  "Tenpiece",
  "Thaddeus",
  "Torsten",
  "Tristan",
  "Urban",
  "Valentin",
  "Valerian",
  "Virgil",
  "Warrick",
  "Waverly",
  "Webster",
  "Wilkin",
  "Wymond",
  "Adelaide",
  "Agnes",
  "Alma",
  "Anastasia",
  "Anika",
  "Annora",
  "Astrid",
  "Barsaba",
  "Beatrix",
  "Bethel",
  "Bianca",
  "Blanche",
  "Bodil",
  "Bridget",
  "Brunhilde",
  "Calypso",
  "Catalina",
  "Cecilia",
  "Celeste",
  "Charlotte",
  "Cleopha",
  "Clotilde",
  "Clover",
  "Colette",
  "Constance",
  "Damaris",
  "Daphne",
  "Demona",
  "Desirae",
  "Ella",
  "Elsbeth",
  "Esme",
  "Eulalia",
  "Euphemia",
  "Eydis",
  "Fern",
  "Fiora",
  "Fleur",
  "Florence",
  "Francesca",
  "Gertrude",
  "Giselle",
  "Godiva",
  "Guinevere",
  "Heloise",
  "Henrietta",
  "Hester",
  "Hippolyta",
  "Honora",
  "Imogene",
  "Ingrid",
  "Ione",
  "Iris",
  "Isabetta",
  "Isolde",
  "Jacquette",
  "Jeanne",
  "Jessamine",
  "Jilly",
  "Lavinia",
  "Lisbet",
  "Madelena",
  "Margot",
  "Marian",
  "Marigold",
  "Matilda",
  "Melisande",
  "Millicent",
  "Minerva",
  "Morgan",
  "Nerissa",
  "Odette",
  "Olga",
  "Olivia",
  "Orchid",
  "Pepper",
  "Petra",
  "Philomena",
  "Phoebe",
  "Piety",
  "Poppy",
  "Portia",
  "Rosalind",
  "Rose",
  "Sabina",
  "Sif",
  "Sigourney",
  "Sigrid",
  "Silence",
  "Sybil",
  "Tabitha",
  "Trillby",
  "Ulfhild",
  "Ursula",
  "Vivian",
  "Wendy",
  "Willow",
  "Winifred",
  "Yvette",
  "Zora"
];

const tablaApellidos1 = [
  "Adder",
  "Apple",
  "Ash",
  "Bab",
  "Bag",
  "Bar",
  "Barrow",
  "Basker",
  "Beau",
  "Beetle",
  "Berry",
  "Bird",
  "Brandy",
  "Bright",
  "Brindle",
  "Bull",
  "Bux",
  "Caven",
  "Chelten",
  "Chester",
  "Chuff",
  "Chum",
  "Clod",
  "Cobble",
  "Cotten",
  "Cress",
  "Crom",
  "Cumber",
  "Dela",
  "Dig",
  "Draw",
  "Dreg",
  "Drol",
  "Dun",
  "Even",
  "Ever",
  "Fair",
  "Fallow",
  "Farthing",
  "Feather",
  "Ferns",
  "Fox",
  "Gam",
  "Gird",
  "Gos",
  "Grey",
  "Grim",
  "Half",
  "Hard",
  "Harrow",
  "Hart",
  "Haver",
  "Hedge",
  "Hither",
  "Holly",
  "Honey",
  "Horn",
  "Kettle",
  "Kings",
  "Little",
  "Long",
  "Love",
  "Middle",
  "Mug",
  "Nether",
  "Never",
  "Obling",
  "Pember",
  "Penning",
  "Pens",
  "Pinker",
  "Porten",
  "Quill",
  "Rath",
  "Sack",
  "Sallow",
  "Salt",
  "Scor",
  "Sedge",
  "Silver",
  "Slither",
  "Smit",
  "Snod",
  "Souther",
  "Stew",
  "Stir",
  "Swine",
  "Tar",
  "Temple",
  "Tide",
  "Tread",
  "Under",
  "Vander",
  "Weather",
  "Wester",
  "Wex",
  "Whit",
  "Wither",
  "Withing",
  "Wy"
];

const tablaApellidos2 = [
  "bald",
  "barrow",
  "batch",
  "beck",
  "blood",
  "bold",
  "bone",
  "bottle",
  "bottom",
  "bridge",
  "buck",
  "burn",
  "bury",
  "by",
  "caster",
  "castle",
  "chester",
  "child",
  "church",
  "cliff",
  "cloth",
  "coat",
  "combe",
  "cott",
  "dale",
  "dish",
  "ditch",
  "down",
  "fax",
  "feld",
  "fent",
  "fer",
  "field",
  "foot",
  "force",
  "fort",
  "fry",
  "gale",
  "grass",
  "grave",
  "green",
  "grove",
  "ham",
  "hill",
  "hope",
  "lack",
  "lain",
  "land",
  "less",
  "lin",
  "ling",
  "lish",
  "lock",
  "long",
  "low",
  "ly",
  "man",
  "march",
  "mark",
  "marl",
  "marsh",
  "mass",
  "meer",
  "mond",
  "mont",
  "mor",
  "morn",
  "nick",
  "ny",
  "port",
  "ridge",
  "row",
  "sea",
  "set",
  "shot",
  "sop",
  "spoon",
  "staff",
  "stoke",
  "stone",
  "ten",
  "thorn",
  "thorpe",
  "throp",
  "ton",
  "tooth",
  "top",
  "vane",
  "ville",
  "wald",
  "wark",
  "watch",
  "water",
  "well",
  "whistle",
  "wick",
  "wood",
  "worm",
  "worth",
  "worthy"
];

const tablaPersonalidades = [
  "Siempre aburrido",
  "Ansioso",
  "Arquetipo (p. 53)",
  "Arrogante",
  "Franco",
  "Autoritario",
  "Fanfarrón",
  "Matón",
  "Actitud positiva",
  "Charlatán",
  "Animado",
  "Afable",
  "Competitivo",
  "Mentiroso compulsivo",
  "Condescendiente",
  "Maquinador",
  "Valiente",
  "Cobarde",
  "Siniestro",
  "Críptico",
  "Apuesto",
  "Decadente",
  "Despistado",
  "Dogmático",
  "Ocurrente",
  "Gastrónomo",
  "Fanático",
  "Mujer fatal",
  "Ferozmente leal",
  "Extravagante",
  "Coqueto",
  "Campechano",
  "Formal",
  "Generoso",
  "Misofóbico",
  "Glotón",
  "Chismoso",
  "Crédulo",
  "Curtido",
  "Rencoroso",
  "Honorable",
  "Irascible",
  "Sin sentido del humor",
  "Idealista",
  "Autoritario",
  "Impulsivo",
  "Inseguro",
  "Intenso",
  "Celoso",
  "Idiota",
  "Torpe",
  "Sabelotodo",
  "Conoce a todo el mundo",
  "Lógico",
  "Enamorado",
  "Maníaco",
  "Melancólico",
  "Misántropo",
  "Tacaño",
  "Mórbido",
  "Ingenuo",
  "Narcisista",
  "Empollón",
  "No se rinde nunca",
  "Obsesivo",
  "Demasiado precavido",
  "Paranoico",
  "Patriótico",
  "Pedante",
  "Modales perfectos",
  "Perfeccionista",
  "Piadoso",
  "Sediento de poder",
  "Prejuicioso",
  "Arisco",
  "Proselitista",
  "Justiciero",
  "Disciplina rígida",
  "Despiadado",
  "Sádico",
  "Sarcástico",
  "Autocompasivo",
  "Sereno",
  "Escéptico",
  "Vago",
  "Desaliñado",
  "Soplón",
  "Estirado",
  "Sofista",
  "Distraído",
  "Supersticioso",
  "Memoria terrible",
  "Cerrado de mente",
  "Lamebotas",
  "Totalmente poco fiable",
  "Honesto",
  "Tenso",
  "Quejica",
  "Bocazas",
  "Ocurrente"
];

const tablaCarreras = [
  "acólito: candelabro, incensario, incienso",
  "acróbata: polvo flash, pelotas, aceite de lámpara",
  "actor: peluca, maquillaje, disfraz",
  "alquimista: ácido, mortero/mazo, 6 frascos",
  "anticuario: moneda antigua, bandera, libro de historia",
  "arcanista: grimorio, túnicas arcanas, tiza",
  "arquitecto: plomada, nivel, regla",
  "asesino: ballesta, garrote, botas blandas",
  "astrólogo: cartas estelares, almanaque, telescopio",
  "panadero: rodillo, saco de harina, bloque de manteca",
  "bandido: máscara, grilletes, caltrops",
  "barbero: tijeras, aceite capilar, navaja",
  "domador: látigo, guantes, correa",
  "apicultor: miel, máscara, bomba de humo",
  "herrero: martillo, fuelle, tenazas",
  "barquero: pértiga de 3 m, instrumento, remo",
  "encuadernador: costurero, pegamento, pluma/tinta",
  "cervecero: pala de mezcla, barril de cerveza, lúpulo",
  "ladrón: ganzúas, garfio con cuerda, cuerda",
  "carnicero: cuchillo grande, gancho para carne, panceta",
  "velero: 10 velas, aceite de lámpara, cera",
  "carpintero: martillo, sierra, caja de clavos",
  "charlatán: disfraz, elixir falso, diploma falso",
  "zapatero: rollo de cuero, zapatos elegantes, tachuelas",
  "cochero: látigo, caja fuerte, abrigo impermeable",
  "cocinero: sartén, sal, aceite de oliva",
  "mensajero: bolsa impermeable, mapa local, linterna",
  "cortesano: perfume, peluca, abanico",
  "cultista: daga, túnica ritual, amuleto",
  "carterista: cuchillo, caltrops, saco",
  "tintorero: pértiga de 3 m, tintes, jabón",
  "explorador: sextante, catalejo, crampones",
  "halconero: jaula, guantes, silbato",
  "reducidor: espada corta, lima, lacre",
  "pescador: lanza, red, equipo de pesca",
  "folclorista: profecía, huesos, balanza",
  "jugador: estoque, baraja, dados",
  "guardabosques: honda, cuerno, escalera de cuerda",
  "jardinero: hoz, pala, tijeras de podar",
  "saqueador de tumbas: sierra, palanca, poleas",
  "enterrador: pala, pico, cubo",
  "mozo de cuadra: avena, cepillo para caballo, manta",
  "guardia: alabarda, librea, cuerno",
  "verdugo: hacha, capucha, garrote",
  "herbolario: hierbas, hoz, manual de hierbas",
  "ermitaño: bastón, hongos, cesta",
  "cazador: tienda, piel de oso, trampa para osos",
  "posadero: cucharón, 10 velas, caldero",
  "inquisidor: manual, vestiduras, alicates",
  "investigador: diario, grilletes, frasco",
  "carcelero: candado, cadena de 3 m, jarra de vino",
  "bufón: cetro, cabeza de burro, traje de bufón",
  "joyero: alicates, lupa, pinzas",
  "caballero: pañuelo de dama, estandarte, anillo de sello",
  "secuestrador: cloroformo, grilletes, capucha",
  "abogado: toga elegante, código legal, certificado",
  "cerrajero: palanca, ganzúas, candado",
  "albañil: cincel, martillo, tiza",
  "mercader: balanza, cofre fuerte, bolsa de especias",
  "minero: pico, linterna, canario mascota",
  "músico: 3 instrumentos",
  "naturalista: fósil, caja de insectos, geoda",
  "oficial: betún, medalla, catalejo",
  "oráculo: hojas de té, tarot, cristal",
  "orador: 100 canicas, megáfono, tablilla de cera",
  "pintor: aceite de linaza, pigmentos, pinceles",
  "vendedor ambulante: cubo, 90 m de cuerda, espejo",
  "filósofo: bastón, linterna, tiza",
  "médico: sierra, bisturí, jarra de vino",
  "peregrino: bastón, reliquia, carta de paso",
  "pirata: sextante, bala de cañón, garfio con cuerda",
  "luchador: red, látigo, jarra de vino",
  "dramaturgo: pluma/tinta, calavera, 10 velas",
  "furtivo: aroma animal, arco, 20 flechas",
  "poeta: papelería, campana, perfume",
  "sacerdote: agua bendita, 10 estacas, libro de oraciones",
  "buscador de oro: 10 picas de hierro, pico, sartén",
  "titiritero: confeti, títere, costurero",
  "cazador de ratas: jaula, 10 trampas, saco",
  "saboteador: vejiga de aire, palanca, bomba",
  "marinero: cera de abejas, poleas, catalejo",
  "vigía: banderas, grasa negra, dados",
  "escribano: aceite de lámpara, pluma/tinta, lacre",
  "escultor: cincel, arcilla, calibradores",
  "sirviente: esponja, cubertería, atizador",
  "pastor: cayado, instrumento, honda",
  "constructor naval: taladro, martillo, hacha",
  "cantante: espejo, maquillaje, relicario",
  "contrabandista: poleas, cuerda, maquillaje",
  "soldado: tienda, baraja, pala",
  "espía: caltrops, veneno, documentos falsos",
  "escudero: antorcha, pulidor de armadura, trompeta",
  "sastre: costurero, tijeras, jabón",
  "tatuador: olla de hollín, agujas, 10 velas",
  "cazador de criminales: trampa, grilletes, antorcha",
  "matón: veneno, cuchillo, aceite de lámpara",
  "torturador: taladro, reloj de arena, cadena de 3 m",
  "trampista: trampa para osos, 90 m de cuerda, piel de oso",
  "vigilante: linterna, trompeta, lanza",
  "leñador: hacha, leña, cuerda de 15 m"
];

const tablaDetalles = [
  "Cicatriz por ácido",
  "Rostro aquilino",
  "Cicatriz de flecha",
  "Atlético",
  "Mala vista",
  "Calvo",
  "Entrando en calvicie",
  "Hermoso",
  "Marca de nacimiento",
  "Mordedura",
  "Cicatriz de cuchilla",
  "Ciego",
  "Rostro tosco",
  "Huesudo",
  "Cabello trenzado",
  "Musculoso",
  "Cabello erizado",
  "Nariz rota",
  "Cicatriz por quemadura",
  "Cejas tupidas",
  "Rostro infantil",
  "Rostro cincelado",
  "Cicatriz de garra",
  "Peinado elegante",
  "Corpulento",
  "Rostro escarpado",
  "Dientes torcidos",
  "Cabello rapado",
  "Cabello rizado",
  "Sordo",
  "Rostro delicado",
  "Rastas",
  "Cabello sucio",
  "Fofo",
  "Rostro plano",
  "Frágil",
  "Pecas",
  "Rostro arrugado",
  "Demacrado",
  "Diente de oro",
  "Dificultad para oír",
  "Enorme",
  "Desgarbado",
  "Mandíbula prominente",
  "Cojea",
  "Rostro abultado",
  "Cabello lujoso",
  "Falta un brazo",
  "Falta una oreja",
  "Falta un ojo",
  "Falta un dedo",
  "Falta un pie",
  "Falta una mano",
  "Falta una pierna",
  "Dientes perdidos",
  "Mutación (p. 30)",
  "Mudo",
  "Sin cejas",
  "Cicatriz de soga",
  "Grasiento",
  "Corte paje",
  "Postura perfecta",
  "Perfumado",
  "Piercings",
  "Rostro afilado",
  "Coleta",
  "Cicatrices de viruela",
  "Músculos marcados",
  "Cicatriz ritual",
  "Rostro sonrosado",
  "Dientes podridos",
  "Rostro redondo",
  "Agreste",
  "Escuálido",
  "Cabello desgreñado",
  "Dientes afilados",
  "Marchito",
  "Cabello sedoso",
  "Fibroso",
  "Delgado",
  "Cabello engominado",
  "Encorvado",
  "Maloliente",
  "Rostro cuadrado",
  "Bizco",
  "Escultural",
  "Robusto",
  "Sudoroso",
  "Tatuado",
  "Pequeño",
  "Moño alto",
  "Imponente",
  "Labio torcido",
  "Cabello muy largo",
  "Verrugas",
  "Cabello ondulado",
  "Rostro curtido",
  "Esbelto",
  "Fibroso",
  "Cabello ralo"
];

const tablaObjetivos = [
  "Alcanzar la santidad",
  "Conseguir seguidores",
  "Adquirir tierras",
  "Acumular riquezas",
  "Asesorar al líder",
  "Asombrar a la ciudad",
  "Evitar ser detectado",
  "Alcanzar la libertad",
  "Volverse infame",
  "Volverse erudito",
  "Limpiar la región",
  "Recolectar artefactos",
  "Conquistar una ciudad",
  "Conquistar una región",
  "Controlar una ciudad",
  "Controlar una facción",
  "Controlar la magia",
  "Controlar el ejército",
  "Controlar la política",
  "Controlar la religión",
  "Controlar el comercio",
  "Crear un ejército",
  "Crear una obra de arte",
  "Establecer una base",
  "Fundar una ciudad",
  "Crear una enfermedad",
  "Crear una mazmorra",
  "Fundar una facción",
  "Formar una familia",
  "Construir una máquina",
  "Crear un monopolio",
  "Crear un monstruo",
  "Abrir un portal",
  "Debilitar una facción",
  "Curar una enfermedad",
  "Destruir un ejército",
  "Destruir artefactos",
  "Arrasar una ciudad",
  "Eliminar una facción",
  "Eliminar una familia",
  "Erradicar la magia",
  "Abolir la nobleza",
  "Destruir un reino",
  "Erradicar la religión",
  "Destruir el mundo",
  "Desacreditar una facción",
  "Repartir riquezas",
  "Erradicar la pobreza",
  "Poner fin a la guerra",
  "Hacer cumplir la ley",
  "Imponer la moral",
  "Alcanzar la iluminación",
  "Buscar entretenimiento",
  "Lograr fama y gloria",
  "Encontrar justicia",
  "Encontrar el amor",
  "Incriminar una facción",
  "Aterrorizar a la ciudad",
  "Aterrorizar una facción",
  "Ganar respeto",
  "Vengarse",
  "Escuchar rumores",
  "Satisfacer placeres",
  "Unirse a una facción",
  "Entrar en la nobleza",
  "Liderar una facción",
  "Cartografiar lo salvaje",
  "Dominar una habilidad",
  "Misión (p. 51)",
  "Derrocar al gobernante",
  "Pacificar una facción",
  "Proteger artefactos",
  "Proteger las fronteras",
  "Proteger una ciudad",
  "Proteger una facción",
  "Proteger a la familia",
  "Preservar la historia",
  "Proteger al líder",
  "Defender una región",
  "Proteger a los débiles",
  "Publicar obras",
  "Purgar traidores",
  "Resucitar a los muertos",
  "Restaurar una facción",
  "Restaurar al gobernante",
  "Gobernar una ciudad",
  "Gobernar un reino",
  "Dominar el mundo",
  "Sabotear una facción",
  "Ver el mundo",
  "Servir a una deidad",
  "Servir al mal",
  "Servir a una facción",
  "Servir a un líder",
  "Ayudar a los necesitados",
  "Compartir conocimientos",
  "Matar monstruos",
  "Sembrar el caos",
  "Difundir creencias",
  "Sobrevivir a los peligros"
];

const tablaImpedimentos = [
  "Alcohólico",
  "Artritis",
  "Mal líder",
  "Mal mentiroso",
  "En bancarrota",
  "Debe favores",
  "Chantajeado",
  "Ciego",
  "No sabe contar",
  "No sabe leer",
  "Torpe",
  "Condescendiente",
  "Cobarde",
  "Lisiado",
  "Maldito",
  "Sordo",
  "Decadente",
  "Delirio (p. 30)",
  "Seguidores desleales",
  "Desobedece órdenes",
  "Adicto a las drogas",
  "Linaje maligno",
  "Exiliado",
  "Enemigo de una facción",
  "Se desmaya",
  "Enemigo familiar",
  "Coquetea constantemente",
  "Adicto a la comida (p. 49)",
  "Frágil",
  "Adicto al juego",
  "Se mete en peleas",
  "Glotón",
  "Avaricioso",
  "Crédulo",
  "Hemofilia",
  "Horrible",
  "Grandes deudas",
  "Insurreccionista",
  "Celoso",
  "Estafador conocido",
  "Asesino conocido",
  "Ladrón conocido",
  "Traidor conocido",
  "Vándalo conocido",
  "Hazmerreír",
  "Perezoso",
  "Deja pruebas",
  "Ruidoso",
  "De origen humilde",
  "Muchos enemigos",
  "Muchos ex",
  "Migrañas",
  "Enemigo militar",
  "Control mental",
  "Mal informado",
  "Rastro de dinero",
  "Rasgo monstruoso (p. 65)",
  "Mutación (p. 30)",
  "Narcisista",
  "Necesita halagos",
  "Necesita medicación",
  "Sin derechos",
  "No humano",
  "Obeso",
  "Odioso",
  "TOC",
  "Marginado",
  "Paranoico",
  "Paria",
  "Fiestero",
  "Enemigo político",
  "Equipo deficiente",
  "Antecedentes penales",
  "Temerario",
  "Enemigo religioso",
  "Nacimiento escandaloso",
  "Olor (p. 66)",
  "Amante secreto",
  "Convulsiones",
  "Senil",
  "Demasiado sensible",
  "Sonido (p. 66)",
  "Rutinas estrictas",
  "Estúpido",
  "Supersticioso",
  "Vigilado",
  "Sospechoso",
  "Demasiado generoso",
  "Transformado",
  "Anticuado",
  "No-muerto",
  "Impoular",
  "Vampiro",
  "Muy bajo",
  "Se busca",
  "Criminal de guerra",
  "Débil de voluntad",
  "Debilidad (p. 67)",
  "Hombre lobo",
  "Despreciado por todos"
];

const tablaManerismos = [
  "Anécdotas",
  "Arquetipo (p. 53)",
  "Aparte",
  "Autoritario",
  "Atronador",
  "Jadeante",
  "Brusco",
  "Hablador",
  "Alegre",
  "Se ríe solo",
  "Seco",
  "Chulesco",
  "Condescendiente",
  "Conspirador",
  "Canta suavemente",
  "Críptico",
  "Cortante",
  "Inexpresivo",
  "Voz grave",
  "Dramático",
  "Arrastrado",
  "Monótono",
  "Efusivo",
  "Enuncia con claridad",
  "Florido",
  "Gentil",
  "Grave",
  "Ronco",
  "Gruñón",
  "Entre cortado",
  "Hipo",
  "Muy formal",
  "Histérico",
  "Afonía",
  "Meloso",
  "Susurrante",
  "Hiperbólico",
  "Hipnótico",
  "Incoherente",
  "Insistente",
  "Interrumpe",
  "Lacónico",
  "Lánguido",
  "Melódico",
  "Pausas largas",
  "Melodioso",
  "Monosilábico",
  "Monótono",
  "Masculla",
  "Menciona nombres importantes",
  "Narra en voz alta",
  "Nasales",
  "Amenazante",
  "Demasiado confiado",
  "Demasiado informal",
  "Pedante",
  "Lleno de tópicos",
  "Pesado",
  "Pontifica",
  "Preciso",
  "Remilgado",
  "Profano",
  "Profesoral",
  "Ronronea",
  "Dichos pintorescos",
  "Callado",
  "Tembloroso",
  "Cita frases",
  "Divaga",
  "Datos aleatorios",
  "Despotrica",
  "Ametralladora verbal",
  "Ronco",
  "Resonante",
  "Habla en rima",
  "Rítmico",
  "Robótico",
  "Sarcástico",
  "Seductor",
  "Estridente",
  "Canta al hablar",
  "Habla lento",
  "Balbucea",
  "Burlón",
  "Sonoro",
  "Reconfortante",
  "Sonido (p. 66)",
  "Discursivo",
  "Chillón",
  "Jerga callejera",
  "Tartamudea",
  "Habla consigo mismo",
  "Se desvanece",
  "Demasiado sincero",
  "Vitriólico",
  "La voz se le quiebra",
  "Cálido",
  "Susurra",
  "Melancólico",
  "Irónico"
];
