const tablaTarot = [
["00-TheFool.jpg", "El Loco: confianza, inocencia, mente abierta, comienzo, instinto"], 
["01-TheMagician.jpg", "El Mago: poder personal, intención, voluntad, inventinva"], 
["02-TheHighPriestess.jpg", "La Sacerdotisa: sabiduría interior, receptividad, espiritualidad, meditación"], 
["03-TheEmpress.jpg", "La Emperatriz: criar, creatividad, sensualidad, madre"], 
["04-TheEmperor.jpg", "El Emperador: poder, estructura, estabilidad, autoridad, padre"], 
["05-TheHierophant.jpg", "El Hierofante: maestro, sistema de creencias, conocimiento, concienzudo, responsabilidad"], 
["06-TheLovers.jpg", "Los Amantes: amor, unión, cooperación, elección, sexualidad"], 
["07-TheChariot.jpg", "El Carro: impulso, competencia, auto-disciplina, control, determinación"], 
["08-Strength.jpg", "Fuerza: impulsos instintivos, fuerza interior, supervivencia, coraje"], 
["09-TheHermit.jpg", "El Ermitaño: soledad, introspección, perspectiva, sabiduría, guía"], 
["10-WheelOfFortune.jpg", "Rueda De La Fortuna: pasar a la acción, cambio, movimiento, destino, suerte, expansión"], 
["11-Justice.jpg", "Justicia: justicia, balance, ética, ley, responsabilidad"], 
["12-TheHangedMan.jpg", "El Colgado: rendirse, nueva perspectiva, espera, sacrificio, liberación"], 
["13-Death.jpg", "Muerte: transformación, fin, conclusión, regeneración"], 
["14-Temperance.jpg", "Templanza: combinando, creando, compromiso, experimentación"], 
["15-TheDevil.jpg", "El Diablo: apegos, restricciones, compromiso, limitaciones"], 
["16-TheTower.jpg", "La Torre: conmoción repentina, destrucción, cuestionarse las creencias, caos"], 
["17-TheStar.jpg", "La Estrella: optimismo, renovación, sin límites, paz, astrología"], 
["18-TheMoon.jpg", "La Luna: lo inconsciente, la parte oscura de ser, confusión, sueños, intuición"], 
["19-TheSun.jpg", "El Sol: entusiasmo, alegría, claridad, crecimiento personal, auto-aceptación"], 
["20-Judgement.jpg", "Juicio: rito iniciático, madurar, revisión, transición"], 
["21-TheWorld.jpg", "El Mundo: integración, completitud, opciones, totalidad, la Tierra, conexión"], 
["Cups01.jpg", "As de copas: nuevos sentimientos, nuevo amor, despertar de la intuición, afloramiento de emociones, imaginación"], 
["Cups02.jpg", "Dos de copas: igualdad, amor, respeto, compartir, armonía"], 
["Cups03.jpg", "Tres de copas: amistad, celebración, diversión, ritual"], 
["Cups04.jpg", "Cuatro de copas: abstinencia, indiferencia, insatisfacción, aburrimiento, estar en las nubes"], 
["Cups05.jpg", "Cinco de copas: tristeza, duelo, disgustado, arrepentimiento, sufrimiento, ajuste emocional"], 
["Cups06.jpg", "Seis de copas: amabilidad, cuidar, nostalgia, recuerdos, niñez"], 
["Cups07.jpg", "Siete de copas: fantasía, ilusión, brainstorming creativo, estados alterados"], 
["Cups08.jpg", "Ocho de copas: búsqueda espiritual, dejar algo atrás, darse espacio, retirada, viaje"], 
["Cups09.jpg", "Nueve de copas: deseos cumplidos, satisfacción, exceso, anfitrión"], 
["Cups10.jpg", "Diez de copas: hogar feliz, amor mutuo, bendiciones, paz, familia"], 
["Cups11.jpg", "Jota de copas: sensible, amable, imaginativo, romántico, tierno, nuevo amor, cartas de amor"], 
["Cups12.jpg", "Caballo de copas: romántico, buscando el amor, voluble, intensidad emocional, idealismo, búsqueda espiritual, artista, ligar"], 
["Cups13.jpg", "Reina de copas: empático, receptivo, sensible, introspectivo, psíquico, emocional, amante, soñador, consejero, madre"], 
["Cups14.jpg", "Rey de copas: sabio, emocionalmente maduro, experimentado, sereno, calmado, curador, consejero, padre"], 
["Pentacles01.jpg", "As de oros: oportunidad, comienzo sano, inversión, plantar semillas, realista"], 
["Pentacles02.jpg", "Dos de oros: adaptabilidad, cambios, multitarea, jugar"], 
["Pentacles03.jpg", "Tres de oros: ayuda, contribución, mentores, planificación, trabajo en equipo, conseguir trabajo"], 
["Pentacles04.jpg", "Cuatro de oros: estable, precavido, proteger recursos, límites, ahorro"], 
["Pentacles05.jpg", "Cinco de oros: falta de seguridad, inestabilidad, pensamiento de escasez, prejuicios, enfermedad, apoyo de amigos"], 
["Pentacles06.jpg", "Seis de oros: flujo financiero, caridad, asistencia, devolver el favor, generosidad"], 
["Pentacles07.jpg", "Siete de oros: evaluación, paciencia, prueba y error, feedback, edición"], 
["Pentacles08.jpg", "Ocho de oros: trabajo que sirve, precisión, compromiso, almacenar, repetición"], 
["Pentacles09.jpg", "Nueve de oros: recompensas merecidas, fruto del trabajo, lujo, autosuficiencia, disciplina"], 
["Pentacles10.jpg", "Diez de oros: legado, permanencia, riqueza, ancestros, sabiduría, hogar"], 
["Pentacles11.jpg", "Jota de oros: práctico, cauteloso, estudiante, nuevo trabajo o proyecto, nueva inversión, nuevos estudios"], 
["Pentacles12.jpg", "Caballo de oros: leal, confiable, práctico, buen trabajador, cauteloso, atención al detalle"], 
["Pentacles13.jpg", "Reina de oros: protector, criar, con recursos, abundancia, realista, fértil, sano, ecológico, ama de casa, madre"], 
["Pentacles14.jpg", "Rey de oros: rico, exitoso, práctico, materialista, cabezota, conservador, jefe, padre cariñoso"], 
["Swords01.jpg", "As de espadas: realización, verdad, intelecto, claridad, comunicación"], 
["Swords02.jpg", "Dos de espadas: indecisión, imparcial, mediador, bloqueo"], 
["Swords03.jpg", "Tres de espadas: pérdida, pena, traición, sacrificio necesario"], 
["Swords04.jpg", "Cuatro de espadas: descanso, reflexión, descanso mental, incubar ideas, vacaciones"], 
["Swords05.jpg", "Cinco de espadas: derrota, auto derrota, discusiones, irritabilidad, sentirse atacado"], 
["Swords06.jpg", "Seis de espadas: transición, sanar mentalmente, retirada, apoyo, movimiento, viaje en agua"], 
["Swords07.jpg", "Siete de espadas: estrategia, examen mental, decepción, recogida de información, romper acuerdos"], 
["Swords08.jpg", "Ocho de espadas: pensamientos de indefensión, ponerse límites, auto crítica, excusas, mentalidad víctima"], 
["Swords09.jpg", "Nueve de espadas: preocupación, ansiedad, insomnio, pensamientos reprimidos"], 
["Swords10.jpg", "Diez de espadas: tocar fondo, acabado, rendirse, cierre"], 
["Swords11.jpg", "Jota de espadas: reflexivo, curioso, intelectual, escritor, estudiante"], 
["Swords12.jpg", "Caballo de espadas: revolucionario, filosófico, impaciente, con prisas, explorador, debate"], 
["Swords13.jpg", "Reina de espadas: inteligente, sincero, buen comunicador, consciente, independiente, maestro, escritor"], 
["Swords14.jpg", "Rey de espadas: objetivo, lógico, inteligente, justo, autoritativo, asertivo, emocionalmente distante"], 
["Wands01.jpg", "As de bastos: nacimiento, energía, inspiración, sexualidad, auto-imagen"], 
["Wands02.jpg", "Dos de bastos: elección, potencial, contemplación, umbral, planificación"], 
["Wands03.jpg", "Tres de bastos: lanzamiento, planes a largo plazo, previsión, poner cosas en movimiento"], 
["Wands04.jpg", "Cuatro de bastos: resultados, recompensas, celebración, trabajo en equipo, gratitud, hogar"], 
["Wands05.jpg", "Cinco de bastos: competición, brainstorming, resolver problemas, conflicto"], 
["Wands06.jpg", "Seis de bastos: reconocimiento, modelo a seguir, promoción, alabar, confianza en uno mismo"], 
["Wands07.jpg", "Siete de bastos: defender lo que merece la pena, amenaza, perseverancia"], 
["Wands08.jpg", "Ocho de bastos: rapidez, progreso, energía, viaje aereo"], 
["Wands09.jpg", "Nueve de bastos: herido, experimentado, cauto, perseverancia, reservas internas"], 
["Wands10.jpg", "Diez de bastos: responsabilidad, carga, obligaciones, éxito, estrés"], 
["Wands11.jpg", "Jota de bastos: entusiasta, aventurero, inspirado, nuevo deseo, nueva identidad, nueva idea, nuevo viaje, noticias inspiradoras"], 
["Wands12.jpg", "Caballo de bastos: aventurero, arriesgarse, experimental, diversión, apasionado, viaje"], 
["Wands13.jpg", "Reina de bastos: creativo, independiente, seguro de sí mismo, bello, apasionado, amigable, optimista, influyente, sexual"], 
["Wands14.jpg", "Rey de bastos: auténtico, líder, apasionado, carismático, experimentado, enérgico, influyente, orgulloso, sexual"], 
];
